# Generated by Django 5.2.17 on 2026-10-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('streak', models.PositiveIntegerField(default=0)),
                ('last_completed', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
