# Generated by Django 5.2.17 on 2026-10-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddField(
            model_name='habit',
            name='emoji',
            field=models.CharField(default='✨', max_length=12),
        ),
        migrations.AddField(
            model_name='habit',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
