# Generated by Django 5.2.17 on 2026-10-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_options_habit_emoji_habit_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={},
        ),
        migrations.RemoveField(
            model_name='habit',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='position',
        ),
    ]
